#!/bin/bash
# restart - restart the cluster

set -eu

benchdir="$HOME/src/fk-bench"
. $benchdir/lib.sh

function usage() {
  echo "USAGE: restart {range_agg|lag|exists}"
  exit 1
}

impl="${1:-}"
use_impl "$impl" || usage

# restart postgres
pg_ctl -D "$datadir" -l "$log" restart
